### ISSUE TITLE
Time submitted changed to milliseconds

### ISSUE THREAD

**Issue by eshtadc** [bryanbraun/petitions-newslink#10]
I see that the back-end is now returning in milliseconds.  This had caused the application to stop returning petition and news matches because I was already adjusting for receiving these times in seconds.  I have adjusted my code to expect milliseconds now to adjust.

@typesend I don't know how to re-compile the data at heroku in order to see the changes.  Once its in there I can take a look at the error @bryanbraun had reported.   Will see what I can reproduce in the meantime to troubleshoot.

**Comment by typesend** [comment]
Thanks @lkhaas! Hey @bryanbraun! Just pushed the changes to Heroku.  Since you both have Macbooks, configuring yourselves to run the Rails 4 app locally, as well as push changes to Heroku, is fairly straightforward:

https://devcenter.heroku.com/articles/quickstart

Steps one, two, and three are about making your machine aware of your heroku account and vice versa.  Once you have this part done you can technically deploy code changes at the command line with a: `git push heroku master`

Their step four isn't exactly what you want to do, since I've already gotten the heroku app bootstrapped and have deployed more than once.  I'm guessing that neither of you have Ruby 1.9, rubygems, and Rails installed already, so that is really your biggest next step.

I'd send you instructions for doing this now but there are several different ways to install the rails stack and everyone has differing opinions on which way is best for them and how they like to control their system configuration.  Here are a few different approaches to google for more info on. Email me directly if you want help choosing or for detailed help once you have picked a method of installing things.  (I generally use and like Homebrew, but to each their own...)
- Homebrew
- rbenv
- railsinstaller.org

Once you have Rails installed on your system, there are a few commands you'll want to run from inside the root directory of the source files:
1. `bundle install` will install all the gems our application depends on (as defined in the Gemfile)
2. `rake db:setup` will create a local sqlite3 db with the correct schema, and then load the seed data into it by making a all to the petitions API. (To refresh the data later you can `rake db:seed`)
3. `rails server` will start up the application locally so you can play with it at _http://localhost:3000_

Anytime you are deploying frontend code changes you should always `RAILS_ENV=production rake assets:precompile`. This basically concatenates our JS and CSS code into minified, singular files to improve performance of those assets in production. Then you should `git commit` and `git push heroku master` to actually deploy.

An excellent overview of all the key features of Rails can be found at http://guides.rubyonrails.org and of course I'm happy to help you out along the way. :)  Apologies in advance if I have overlooked a step. Oh, if you're generally curious about how things are done in Rails you might enjoy the screencasts at http://railscasts.com.

**Comment by eshtadc** [comment]
Fantastic @typesend 
I'm almost all the way through the installs and hope to get this up and running soon.
